//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProInvesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public string Bank_Name { get; set; }
        public string Interest_Rate_Range { get; set; }
        public string Processing_Fee_Range { get; set; }
        public string Loan_Amount { get; set; }
        public string Tenure_Range { get; set; }
        public string LoanType { get; set; }
        public int ID { get; set; }
    }
}
