//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProInvesta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanData
    {
        public int ID { get; set; }
        public int Loan_No { get; set; }
        public Nullable<decimal> Loan_Amount { get; set; }
        public Nullable<System.DateTime> Login_Date { get; set; }
        public string Mobile_No { get; set; }
        public string Sourcing_Branch { get; set; }
        public string Rinn_Raksha { get; set; }
        public string Sourcing_Person { get; set; }
        public string Loan_Type { get; set; }
        public string Name { get; set; }
        public string createdby { get; set; }

    }
}
